/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Logica.NumComplejo;
import javax.swing.JPanel;

/**
 *
 * @author futbo
 */
public class Graficador extends javax.swing.JFrame {
        public String[] colores = {"rojo","azul","verde","naranja", "cyan", "gray", "magente", "rosa", "amarillo", "blanco"};

    private int scala =0;
    public Grafica uwu;
    private NumComplejo[] aciertos;
    /**
     * Creates new form Graficador
     */
    public Graficador(NumComplejo[] aciertos, int scala) {
        initComponents();
        this.aciertos = aciertos;
        this.scala=scala;
        jl_escala.setText("Escala 1:"+this.scala);
         uwu=new Grafica(aciertos,scala);
        jp_Grafica.add(uwu);
        for(int i =0;i<aciertos.length;i++){
            jta_area.setText(jta_area.getText()+"\n"+"z"+(i+1)+":"+aciertos[i].toEuler()+": "+colores[i]);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_Grafica = new javax.swing.JPanel();
        btn_zoomp = new javax.swing.JButton();
        btn_zoomm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_area = new javax.swing.JTextArea();
        jl_escala = new javax.swing.JLabel();

        javax.swing.GroupLayout jp_GraficaLayout = new javax.swing.GroupLayout(jp_Grafica);
        jp_Grafica.setLayout(jp_GraficaLayout);
        jp_GraficaLayout.setHorizontalGroup(
            jp_GraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jp_GraficaLayout.setVerticalGroup(
            jp_GraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        btn_zoomp.setText("+");
        btn_zoomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zoompActionPerformed(evt);
            }
        });

        btn_zoomm.setText("-");
        btn_zoomm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zoommActionPerformed(evt);
            }
        });

        jta_area.setEditable(false);
        jta_area.setColumns(20);
        jta_area.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jta_area.setRows(5);
        jScrollPane1.setViewportView(jta_area);

        jl_escala.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jl_escala.setText("Escala:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btn_zoomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_zoomm))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jp_Grafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_escala, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_Grafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jl_escala)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_zoomp)
                    .addComponent(btn_zoomm))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_zoompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zoompActionPerformed
        switch(scala){
            case 10:
                scala=20;
                
//                (new Graficador(this.aciertos,scala)).setVisible(true);
//                this.setVisible(false);
                break;
            case 20:
                scala=40;
                
//                (new Graficador(this.aciertos,scala)).setVisible(true);
//                this.setVisible(false);
                break;
            case 40:
                scala=50;
                
//                (new Graficador(this.aciertos,scala)).setVisible(true);
//                this.setVisible(false);
                break;
            case 50:
                scala=100;
                
//                (new Graficador(this.aciertos,scala)).setVisible(true);
//                this.setVisible(false);
                break;
            default:
               break;
        }
        uwu.scala = scala;
        uwu.updateUI();
                // TODO add your handling code here:
    }//GEN-LAST:event_btn_zoompActionPerformed

    private void btn_zoommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zoommActionPerformed
    switch(scala){
            case 20:
                scala=10;
//                (new Graficador(this.aciertos,scala)).setVisible(true);
//                this.setVisible(false);
                break;
            case 40:
                scala=20;
//                (new Graficador(this.aciertos,scala)).setVisible(true);
//                this.setVisible(false);break;
            case 50:
                scala=40;
//                (new Graficador(this.aciertos,scala)).setVisible(true);
//                this.setVisible(false);break;
            case 100:
                scala=50;
//                (new Graficador(this.aciertos,scala)).setVisible(true);
//                this.setVisible(false);break;
            default:
                scala=10;
                break;
        }// TODO add your handling code here:
        uwu.scala = scala;
        uwu.updateUI();
    }//GEN-LAST:event_btn_zoommActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        NumComplejo[] muestra = new NumComplejo[2];
        muestra[1]= new NumComplejo((double)3,(double)2);
        muestra[0] = new NumComplejo((double)2,(double)2);
        
        (new Graficador(muestra,10)).setVisible(true);
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_zoomm;
    private javax.swing.JButton btn_zoomp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jl_escala;
    private javax.swing.JPanel jp_Grafica;
    private javax.swing.JTextArea jta_area;
    // End of variables declaration//GEN-END:variables
}
