/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Logica.NumComplejo;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author futbo
 */
public class Operaciones extends javax.swing.JFrame {
    public NumComplejo z1;
    public NumComplejo z2;
    public NumComplejo z3;
    public boolean ez1=false;
    public boolean ez2=false;
    public boolean ez3=false;
    public  int contador = 0;
    public static Operaciones o = new Operaciones();
    
    /**
     * Creates new form Operaciones
     */
    public Operaciones() {
        this.setName("Calculadora");
        initComponents();
        jtf_z1.setText("");
        jtf_z2.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtf_z1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtf_z1_trigonometrica = new javax.swing.JTextField();
        jtf_z1_euler = new javax.swing.JTextField();
        btn_est1 = new javax.swing.JButton();
        btn_trig1 = new javax.swing.JButton();
        btn_euler1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_conjugado1 = new javax.swing.JButton();
        btn_potencia1 = new javax.swing.JButton();
        num_potencia1 = new javax.swing.JComboBox<>();
        btn_raiz1 = new javax.swing.JButton();
        num_raiz1 = new javax.swing.JComboBox<>();
        btn_flush1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jtf_z2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtf_z2_trigonometrica = new javax.swing.JTextField();
        jtf_z2_euler = new javax.swing.JTextField();
        btn_est2 = new javax.swing.JButton();
        btn_trig2 = new javax.swing.JButton();
        btn_euler2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_conjugado2 = new javax.swing.JButton();
        btn_potencia2 = new javax.swing.JButton();
        num_potencia2 = new javax.swing.JComboBox<>();
        btn_raiz2 = new javax.swing.JButton();
        num_raiz2 = new javax.swing.JComboBox<>();
        btn_flush2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btn_suma = new javax.swing.JButton();
        btn_resta = new javax.swing.JButton();
        btn_por = new javax.swing.JButton();
        btn_division = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jtf_enunciado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtf_resultado = new javax.swing.JTextField();
        jtf_reseuler = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtf_restrig = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btn_toz1 = new javax.swing.JButton();
        btn_grafica = new javax.swing.JButton();
        btn_toz2 = new javax.swing.JButton();
        btn_flush = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de Complejos");

        jtf_z1.setEditable(false);

        jLabel1.setText("Forma Estandar");

        jLabel2.setText("Forma Trigonometrica");

        jLabel3.setText("Forma de Euler");

        jtf_z1_trigonometrica.setEditable(false);

        jtf_z1_euler.setEditable(false);

        btn_est1.setText("Estandar");
        btn_est1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_est1ActionPerformed(evt);
            }
        });

        btn_trig1.setText("Trigonometrica");
        btn_trig1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trig1ActionPerformed(evt);
            }
        });

        btn_euler1.setText("Euler");
        btn_euler1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_euler1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("Z");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("1");

        btn_conjugado1.setText("Conjugado");
        btn_conjugado1.setEnabled(false);
        btn_conjugado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_conjugado1ActionPerformed(evt);
            }
        });

        btn_potencia1.setText("^");
        btn_potencia1.setEnabled(false);
        btn_potencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_potencia1ActionPerformed(evt);
            }
        });

        num_potencia1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        num_potencia1.setEnabled(false);
        num_potencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_potencia1ActionPerformed(evt);
            }
        });

        btn_raiz1.setText("Raiz");
        btn_raiz1.setEnabled(false);
        btn_raiz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_raiz1ActionPerformed(evt);
            }
        });

        num_raiz1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        num_raiz1.setEnabled(false);

        btn_flush1.setText("A/C");
        btn_flush1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_flush1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_z1_trigonometrica, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_z1_euler, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_z1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_conjugado1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_potencia1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num_potencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_raiz1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(num_raiz1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_trig1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_euler1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_est1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btn_flush1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_z1_trigonometrica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtf_z1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_z1_euler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_euler1)
                    .addComponent(btn_trig1)
                    .addComponent(btn_est1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_flush1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_conjugado1)
                    .addComponent(btn_potencia1)
                    .addComponent(num_potencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_raiz1)
                    .addComponent(num_raiz1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtf_z2.setEditable(false);

        jLabel4.setText("Forma Estandar");

        jLabel5.setText("Forma Trigonometrica");

        jLabel6.setText("Forma de Euler");

        jtf_z2_trigonometrica.setEditable(false);

        jtf_z2_euler.setEditable(false);

        btn_est2.setText("Estandar");
        btn_est2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_est2ActionPerformed(evt);
            }
        });

        btn_trig2.setText("Trigonometrica");
        btn_trig2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trig2ActionPerformed(evt);
            }
        });

        btn_euler2.setText("Euler");
        btn_euler2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_euler2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("2");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setText("Z");

        btn_conjugado2.setText("Conjugado");
        btn_conjugado2.setEnabled(false);
        btn_conjugado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_conjugado2ActionPerformed(evt);
            }
        });

        btn_potencia2.setText("^");
        btn_potencia2.setEnabled(false);
        btn_potencia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_potencia2ActionPerformed(evt);
            }
        });

        num_potencia2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        num_potencia2.setEnabled(false);

        btn_raiz2.setText("Raiz");
        btn_raiz2.setEnabled(false);
        btn_raiz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_raiz2ActionPerformed(evt);
            }
        });

        num_raiz2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        num_raiz2.setEnabled(false);

        btn_flush2.setText("A/C");
        btn_flush2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_flush2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)))
                            .addComponent(btn_trig2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_z2_trigonometrica, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtf_z2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_z2_euler, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addGap(49, 49, 49)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(btn_flush2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_euler2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_est2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_conjugado2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_potencia2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(num_potencia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_raiz2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num_raiz2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_z2_trigonometrica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_z2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtf_z2_euler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_trig2)
                            .addComponent(btn_euler2)
                            .addComponent(btn_est2)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(btn_flush2))
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_conjugado2)
                    .addComponent(btn_potencia2)
                    .addComponent(num_potencia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_raiz2)
                    .addComponent(num_raiz2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Operacion");

        btn_suma.setText("+");
        btn_suma.setEnabled(false);
        btn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumaActionPerformed(evt);
            }
        });

        btn_resta.setText("-");
        btn_resta.setEnabled(false);
        btn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restaActionPerformed(evt);
            }
        });

        btn_por.setText("x");
        btn_por.setEnabled(false);
        btn_por.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_porActionPerformed(evt);
            }
        });

        btn_division.setText("/");
        btn_division.setEnabled(false);
        btn_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divisionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_por, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_suma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_division))
                .addGap(33, 33, 33))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_suma)
                    .addComponent(btn_resta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_por)
                    .addComponent(btn_division))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtf_enunciado.setEditable(false);
        jtf_enunciado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Enunciado:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Trigonometrica");

        jtf_resultado.setEditable(false);
        jtf_resultado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtf_reseuler.setEditable(false);
        jtf_reseuler.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Euler:");

        jtf_restrig.setEditable(false);
        jtf_restrig.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Resultado:");

        btn_toz1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_toz1.setText("Z1");
        btn_toz1.setEnabled(false);
        btn_toz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toz1ActionPerformed(evt);
            }
        });

        btn_grafica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_grafica.setText("G");
        btn_grafica.setEnabled(false);
        btn_grafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_graficaActionPerformed(evt);
            }
        });

        btn_toz2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_toz2.setText("Z2");
        btn_toz2.setEnabled(false);
        btn_toz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toz2ActionPerformed(evt);
            }
        });

        btn_flush.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_flush.setText("A/C");
        btn_flush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_flushActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_enunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_reseuler, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_restrig)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_toz2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_grafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_toz1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_flush)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_grafica, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jtf_enunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtf_reseuler, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(btn_toz2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtf_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_restrig, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(btn_toz1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_flush, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
    z3 = NumComplejo.Suma(z1, z2);
    jtf_enunciado.setText(z1.toString() +" + "+z2.toString());

       load3();
// TODO add your handling code here:
    }//GEN-LAST:event_btn_sumaActionPerformed

    private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
    z3 = NumComplejo.Resta(z1, z2);
    jtf_enunciado.setText(z1.toString() +" - "+z2.toString());
    load3();
    }//GEN-LAST:event_btn_restaActionPerformed

    private void btn_porActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_porActionPerformed
    z3 = NumComplejo.Multiplicacion(z1, z2);
    jtf_enunciado.setText("("+z1.toString() +")("+z2.toString()+")");
    load3();
    }//GEN-LAST:event_btn_porActionPerformed

    private void btn_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisionActionPerformed
    z3= NumComplejo.Division(z1, z2);
    jtf_enunciado.setText(z1.toString() +" / "+z2.toString());
    ez3=true;
    load3();
    }//GEN-LAST:event_btn_divisionActionPerformed

    private void btn_est1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_est1ActionPerformed
    (new PolarGUI1()).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_est1ActionPerformed

    private void btn_est2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_est2ActionPerformed
      (new PolarGUI2()).setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_btn_est2ActionPerformed

    private void btn_conjugado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_conjugado1ActionPerformed
    z3 = NumComplejo.Conjugado(z1);
    jtf_enunciado.setText("!"+z1.toString());
    load3();
    }//GEN-LAST:event_btn_conjugado1ActionPerformed

    private void btn_conjugado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_conjugado2ActionPerformed
     z3 = NumComplejo.Conjugado(z2);
    jtf_enunciado.setText("!"+z2.toString());
    load3();   // TODO add your handling code here:
    }//GEN-LAST:event_btn_conjugado2ActionPerformed

    private void num_potencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_potencia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_potencia1ActionPerformed

    private void btn_potencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_potencia1ActionPerformed
        int i = num_potencia1.getSelectedIndex()+1;
        jtf_enunciado.setText("("+z1.toString()+")^"+i);
        z3=NumComplejo.Potencia(i, z1);
        load3();
        
                // TODO add your handling code here:
    }//GEN-LAST:event_btn_potencia1ActionPerformed

    private void btn_potencia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_potencia2ActionPerformed
    int i = num_potencia2.getSelectedIndex()+1;
    jtf_enunciado.setText("("+z2.toString()+")^"+i);
        z3=NumComplejo.Potencia(i, z2);
        load3();    // TODO add your handling code here:
    }//GEN-LAST:event_btn_potencia2ActionPerformed

    private void btn_graficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_graficaActionPerformed
        NumComplejo[] situaciones;
        if(ez1&&ez2&&ez3){
        situaciones = new NumComplejo[3];
        situaciones[0]=z1;
        situaciones[1]=z2;
        situaciones[2]=z3;
        }
        else if(ez1&&ez3){
        situaciones = new NumComplejo[2];
        situaciones[0]=z1;
        situaciones[1]=z3;
        }
        else{
        situaciones = new NumComplejo[2];
        situaciones[0]=z2;
        situaciones[1]=z3;
        }
        
            new Graficador(situaciones,10).setVisible(true);

            // TODO add your handling code here:
    }//GEN-LAST:event_btn_graficaActionPerformed

    private void btn_toz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toz2ActionPerformed
    z2=z3;
    load_2();// TODO add your handling code here:
    }//GEN-LAST:event_btn_toz2ActionPerformed

    private void btn_flush1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_flush1ActionPerformed
        jtf_z1.setText("");
        jtf_z1_euler.setText("");
        jtf_z1_trigonometrica.setText("");
        btn_suma.setEnabled(false);// TODO add your handling code here:
        btn_resta.setEnabled(false);
        btn_por.setEnabled(false);
        btn_division.setEnabled(false);
        btn_conjugado1.setEnabled(false);
        btn_potencia1.setEnabled(false);
        num_potencia1.setEnabled(false);
        btn_raiz1.setEnabled(false);
        num_raiz1.setEnabled(false);
    }//GEN-LAST:event_btn_flush1ActionPerformed

    private void btn_flush2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_flush2ActionPerformed
     jtf_z2.setText("");
        jtf_z2_euler.setText("");
        jtf_z2_trigonometrica.setText("");
        btn_suma.setEnabled(false);// TODO add your handling code here:
        btn_resta.setEnabled(false);
        btn_por.setEnabled(false);
        btn_division.setEnabled(false);
        btn_conjugado2.setEnabled(false);
        btn_potencia2.setEnabled(false);
        num_potencia2.setEnabled(false);
        btn_raiz2.setEnabled(false);
        num_raiz2.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_flush2ActionPerformed

    private void btn_flushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_flushActionPerformed
        jtf_enunciado.setText("");
        jtf_resultado.setText("");
        jtf_reseuler.setText("");
        jtf_restrig.setText("");
        btn_toz1.setEnabled(false);
        btn_toz2.setEnabled(false);
        btn_grafica.setEnabled(false);
        
        
    }//GEN-LAST:event_btn_flushActionPerformed

    private void btn_euler1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_euler1ActionPerformed
    (new EulerGUI1()).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_euler1ActionPerformed

    private void btn_euler2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_euler2ActionPerformed
    (new EulerGUI2()).setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_btn_euler2ActionPerformed

    private void btn_trig1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trig1ActionPerformed
    (new TrigonometricaGUI1()).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_trig1ActionPerformed

    private void btn_trig2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trig2ActionPerformed
    (new TrigonometricaGUI2()).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_trig2ActionPerformed

    private void btn_toz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toz1ActionPerformed
    z1=z3;
    load_1();// TODO add your handling code here:
    }//GEN-LAST:event_btn_toz1ActionPerformed

    private void btn_raiz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_raiz1ActionPerformed
      (new RaicesGUI(z1,num_raiz1.getSelectedIndex()+1)).setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_btn_raiz1ActionPerformed

    private void btn_raiz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_raiz2ActionPerformed
    (new RaicesGUI(z2,num_raiz2.getSelectedIndex()+1)).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_raiz2ActionPerformed
    public void load_1(){
        jtf_z1.setText(z1.toString());
        jtf_z1_trigonometrica.setText(z1.toTrigonometrica());
        jtf_z1_euler.setText(z1.toEuler());
        ez1=true;
        btn_potencia1.setEnabled(true);
        btn_raiz1.setEnabled(true);
        btn_conjugado1.setEnabled(true);
        num_potencia1.setEnabled(true);
        num_raiz1.setEnabled(true);
        if(ez1&&ez2){
            btn_suma.setEnabled(true);
            btn_resta.setEnabled(true);
            btn_por.setEnabled(true);
            btn_division.setEnabled(true);
        }
        
        
    }
    public void load_2(){
        jtf_z2.setText(z2.toString());
        jtf_z2_trigonometrica.setText(z2.toTrigonometrica());
        jtf_z2_euler.setText(z2.toEuler());
        ez2=true;
        btn_potencia2.setEnabled(true);
        btn_raiz2.setEnabled(true);
        btn_conjugado2.setEnabled(true);
        num_potencia2.setEnabled(true);
        num_raiz2.setEnabled(true);
        if(ez1&&ez2){
            btn_suma.setEnabled(true);
            btn_resta.setEnabled(true);
            btn_por.setEnabled(true);
            btn_division.setEnabled(true);
        }
        
    }
    public void load3(){
        ez3=true;
    btn_toz2.setEnabled(true);
    btn_toz1.setEnabled(true);
    btn_grafica.setEnabled(true);
    jtf_resultado.setText(z3.toString());
    jtf_restrig.setText(z3.toTrigonometrica());
    jtf_reseuler.setText(z3.toEuler());
    }
    /**
     * @param args the command line arguments
     */
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_conjugado1;
    private javax.swing.JButton btn_conjugado2;
    private javax.swing.JButton btn_division;
    private javax.swing.JButton btn_est1;
    private javax.swing.JButton btn_est2;
    private javax.swing.JButton btn_euler1;
    private javax.swing.JButton btn_euler2;
    private javax.swing.JButton btn_flush;
    private javax.swing.JButton btn_flush1;
    private javax.swing.JButton btn_flush2;
    private javax.swing.JButton btn_grafica;
    private javax.swing.JButton btn_por;
    private javax.swing.JButton btn_potencia1;
    private javax.swing.JButton btn_potencia2;
    private javax.swing.JButton btn_raiz1;
    private javax.swing.JButton btn_raiz2;
    private javax.swing.JButton btn_resta;
    private javax.swing.JButton btn_suma;
    private javax.swing.JButton btn_toz1;
    private javax.swing.JButton btn_toz2;
    private javax.swing.JButton btn_trig1;
    private javax.swing.JButton btn_trig2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jtf_enunciado;
    private javax.swing.JTextField jtf_reseuler;
    private javax.swing.JTextField jtf_restrig;
    private javax.swing.JTextField jtf_resultado;
    private javax.swing.JTextField jtf_z1;
    private javax.swing.JTextField jtf_z1_euler;
    private javax.swing.JTextField jtf_z1_trigonometrica;
    private javax.swing.JTextField jtf_z2;
    private javax.swing.JTextField jtf_z2_euler;
    private javax.swing.JTextField jtf_z2_trigonometrica;
    private javax.swing.JComboBox<String> num_potencia1;
    private javax.swing.JComboBox<String> num_potencia2;
    private javax.swing.JComboBox<String> num_raiz1;
    private javax.swing.JComboBox<String> num_raiz2;
    // End of variables declaration//GEN-END:variables
   public static void main(String[] agg){
       o.setVisible(true);
   }
}
