/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Logica.NumComplejo;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JPanel;

/**
 *
 * @author futbo
 */
public class RaicesGUI extends javax.swing.JFrame {
    public NumComplejo[] raices;
    /**
     * Creates new form RaicesGUI
     */
    public RaicesGUI(NumComplejo h, int i) {
        initComponents();
        raices = NumComplejo.raiz(i, h);
        String[] lista = new String[i] ;
        for (int j = 0;j<i;j++){
            lista[j]=raices[j].toEuler();
        }
        jl_raices.setModel((new JList<String>(lista)).getModel());
        jl_raices.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jl_raices = new javax.swing.JList<>();
        btn_recuperar = new javax.swing.JButton();
        btn_Grafica = new javax.swing.JButton();

        jScrollPane1.setViewportView(jl_raices);

        btn_recuperar.setText("Respuesta");
        btn_recuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recuperarActionPerformed(evt);
            }
        });

        btn_Grafica.setText("Grafica");
        btn_Grafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GraficaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_recuperar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Grafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btn_recuperar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Grafica)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_recuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recuperarActionPerformed
    int index=jl_raices.getSelectedIndex();
    Operaciones.o.z3 = raices[index];
    Operaciones.o.load3();
    setVisible(false);
    // TODO add your handling code here:
    }//GEN-LAST:event_btn_recuperarActionPerformed

    private void btn_GraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GraficaActionPerformed

        (new Graficador(raices,10)).setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_btn_GraficaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Grafica;
    private javax.swing.JButton btn_recuperar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jl_raices;
    // End of variables declaration//GEN-END:variables
}
